/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as ManageAccountIndexImport } from './routes/manage-account/index'

// Create Virtual Routes

const NotFoundLazyImport = createFileRoute('/not-found')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const NotFoundLazyRoute = NotFoundLazyImport.update({
  path: '/not-found',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/not-found.lazy').then((d) => d.Route))

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ManageAccountIndexRoute = ManageAccountIndexImport.update({
  path: '/manage-account/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundLazyImport
      parentRoute: typeof rootRoute
    }
    '/manage-account/': {
      id: '/manage-account/'
      path: '/manage-account'
      fullPath: '/manage-account'
      preLoaderRoute: typeof ManageAccountIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AboutRoute,
  NotFoundLazyRoute,
  ManageAccountIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/not-found",
        "/manage-account/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/not-found": {
      "filePath": "not-found.lazy.tsx"
    },
    "/manage-account/": {
      "filePath": "manage-account/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
