/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexcopyImport } from './routes/index copy'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as AboutImport } from './routes/about'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as ManageAccountIndexImport } from './routes/manage-account/index'

// Create Virtual Routes

const NotFoundLazyImport = createFileRoute('/not-found')()

// Create/Update Routes

const NotFoundLazyRoute = NotFoundLazyImport.update({
  path: '/not-found',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/not-found.lazy').then((d) => d.Route))

const IndexcopyRoute = IndexcopyImport.update({
  path: '/index copy',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ManageAccountIndexRoute = ManageAccountIndexImport.update({
  path: '/manage-account/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/index copy': {
      id: '/index copy'
      path: '/index copy'
      fullPath: '/index copy'
      preLoaderRoute: typeof IndexcopyImport
      parentRoute: typeof rootRoute
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundLazyImport
      parentRoute: typeof rootRoute
    }
    '/manage-account/': {
      id: '/manage-account/'
      path: '/manage-account'
      fullPath: '/manage-account'
      preLoaderRoute: typeof ManageAccountIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AboutRoute,
  DashboardRoute,
  IndexcopyRoute,
  NotFoundLazyRoute,
  ManageAccountIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout",
        "/about",
        "/dashboard",
        "/index copy",
        "/not-found",
        "/manage-account/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/index copy": {
      "filePath": "index copy.tsx"
    },
    "/not-found": {
      "filePath": "not-found.lazy.tsx"
    },
    "/manage-account/": {
      "filePath": "manage-account/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
