/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ManageAccountImport } from './routes/manage-account'
import { Route as ConstructionImport } from './routes/construction'
import { Route as IndexImport } from './routes/index'
import { Route as AppIndexImport } from './routes/app/index'

// Create/Update Routes

const ManageAccountRoute = ManageAccountImport.update({
  path: '/manage-account',
  getParentRoute: () => rootRoute,
} as any)

const ConstructionRoute = ConstructionImport.update({
  path: '/construction',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  path: '/app/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/construction': {
      id: '/construction'
      path: '/construction'
      fullPath: '/construction'
      preLoaderRoute: typeof ConstructionImport
      parentRoute: typeof rootRoute
    }
    '/manage-account': {
      id: '/manage-account'
      path: '/manage-account'
      fullPath: '/manage-account'
      preLoaderRoute: typeof ManageAccountImport
      parentRoute: typeof rootRoute
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ConstructionRoute,
  ManageAccountRoute,
  AppIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/construction",
        "/manage-account",
        "/app/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/construction": {
      "filePath": "construction.tsx"
    },
    "/manage-account": {
      "filePath": "manage-account.tsx"
    },
    "/app/": {
      "filePath": "app/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
